config/routes.rb
NewsReader::Application.routes.draw do
  namespace :api do
    resources :feeds, only: [:index, :create, :show, :destroy] do
      resources :entries, only: [:index]
    end
    
    resources :entries, only: [:show]
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: "static_pages#index"
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :feed

  def self.create_from_json!(entryData, feed)
    scrub_encoding(entryData)

    Entry.create!({
      guid: entryData[:guid],
      link: entryData[:link],
      published_at: entryData[:pubDate],
      title: entryData[:title],
      json: entryData.to_json,
      feed_id: feed.id
    })
  end

  def self.scrub_encoding(data)
    data.each do |k, v|
      data[k] = v.is_a?(String) ? v.force_encoding("utf-8") : v
    end
  end
end

app/models/feed.rb
require 'open-uri'

class Feed < ActiveRecord::Base
  validates :title, :url, presence: true
  
  has_many :entries, :dependent => :destroy
  belongs_to :user
  def self.find_or_create_by_url(url, user)
    feed = Feed.find_by(url: url, user_id: user.id)
    return feed if feed

    begin
      feed_data = SimpleRSS.parse(open(url))
      feed = Feed.create!(title: feed_data.title, url: url, user_id: user.id)
      feed_data.entries.each do |entry_data|
        Entry.create_from_json!(entry_data, feed)
      end
    rescue SimpleRSSError
      return nil
    end

    feed
  end

  def reload
    # reloads entries
    self.touch #this causes the updated_at column to be updated
    begin
      feed_data = SimpleRSS.parse(open(url))
      existing_entry_guids = Entry.pluck(:guid).sort
      feed_data.entries.each do |entry_data|
        unless existing_entry_guids.include?(entry_data.guid)
          Entry.create_from_json!(entry_data, self)
        end
      end

      self
    rescue SimpleRSSError
      return false
    end
  end
  
  def latest_entries
    if self.updated_at < 30.seconds.ago
      self.reload
    end
    
    self.entries
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password
  after_initialize :require_session_token
  has_many :feeds, dependent: :destroy
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def reset_session_token
    self.session_token = User.generate_session_token
    self.save
  end
  
  private
  def require_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/api/entries_controller.rb
class Api::EntriesController < ApplicationController
  def index
    feed = Feed.find(params[:feed_id])
    render :json => feed.entries
  end
  
  def show
    entry = Entry.find(params[:id])
    render json: entry
  end
  
  private
  def entry_params
    params.
      require(:entry)
      .permit(:guid, :link, :published_at, :title, :json, :feed_id)
  end
end

app/controllers/api/feeds_controller.rb
class Api::FeedsController < ApplicationController
  def index
    @feeds = current_user.feeds
    render json: @feeds
  end

  def show
    render :json => Feed.find(params[:id]), include: :latest_entries
  end

  def create
    feed = Feed.find_or_create_by_url(feed_params[:url], current_user)
    if feed 
      render :json => feed
    else
      render :json => { error: "invalid url" }, status: :unprocessable_entity
    end
  end
  
  def destroy
    feed = Feed.find(params[:id])
    feed.destroy
    render json: feed
  end

  private

  def feed_params
    params.require(:feed).permit(:title, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?
  
  def redirect_unless_logged_in?
    redirect_to new_session_url unless logged_in?
  end
  
  def logged_in?
    !!current_user
  end
  
  def current_user
    User.find_by(session_token: session[:session_token])
  end
  
  def sign_in(user)
    user.reset_session_token
    session[:session_token] =user.session_token
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user.nil?
      flash.now[:errors] = ["bad sign in"]
      render :new
    else
      sign_in @user
      redirect_to root_url
    end
  end

  def destroy
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :redirect_unless_logged_in?
  
  def index
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">RSSReader</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li>
                <form action="/session"
                      method="POST"
                      >
                    <input type="hidden"
                           name="authenticity_token"
                           value="<%= form_authenticity_token %>">
                    <input type="hidden"
                           name="_method"
                           value="DELETE">
                    <input type="submit", value="Sign Out" id="sign-out-button">
                </form>
            </li>
        <% else %>
            <li><a href="/session/new">Sign In</a></li>
            <li><a href="/users/new">Sign Up</a></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News Reader</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <%= render "layouts/nav" %>

<% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |error| %>
            <li><%= error %></li>
        <% end %>
    </ul>

<% end %>
<div class="container">
    <%= yield %>
</div>
</body>
</html>

app/views/static_pages/index.html.erb
<h1>Hello <%= current_user.username%>!</h1>
<div id='content' class="col-xs-6 col-xs-offset-3"></div>

<script>
    $(document).ready(function(){
      NewsReader.initialize();
    });
</script>

app/views/users/new.html.erb
<h1>New User</h1>
<form action="<%= users_url %>"
      method="POST"
      style="margin:0 auto; width: 20%;">
      
          <input type="hidden"
                 name="authenticity_token"
                 value="<%= form_authenticity_token %>">
      
      <div class="form-group">
      <label for="user_username">Username</label>
      <input type="text"
             name="user[username]"
             id="user_username" class="form-control">
      </div>
      <div class="form-group">
          <label for="user_password">Password</label>
          <input type="password"
                 name="user[password]"
                 id="user_password" class="form-control">
      </div>
        
    <input type="submit" value="Sign Up" class="btn btn-primary">
</form>